// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzojrqeECx2DurObJ8g4xATh7tEcdys0Y',
    appId: '1:551512181966:web:e31fcd09f5f5163117149f',
    messagingSenderId: '551512181966',
    projectId: 'tp-mvp-9014c',
    authDomain: 'tp-mvp-9014c.firebaseapp.com',
    storageBucket: 'tp-mvp-9014c.appspot.com',
    measurementId: 'G-X6VHDHRRP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbUNFW0y0dhh9INq371Qp9QVFZrkE4tk',
    appId: '1:551512181966:android:916b9c2bc0d8fb2917149f',
    messagingSenderId: '551512181966',
    projectId: 'tp-mvp-9014c',
    storageBucket: 'tp-mvp-9014c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXRKwBpoyspLYBK0FWM3KzpBDm1JrJ8Gw',
    appId: '1:551512181966:ios:3983de0a3803e88d17149f',
    messagingSenderId: '551512181966',
    projectId: 'tp-mvp-9014c',
    storageBucket: 'tp-mvp-9014c.appspot.com',
    iosBundleId: 'com.example.mvpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXRKwBpoyspLYBK0FWM3KzpBDm1JrJ8Gw',
    appId: '1:551512181966:ios:3983de0a3803e88d17149f',
    messagingSenderId: '551512181966',
    projectId: 'tp-mvp-9014c',
    storageBucket: 'tp-mvp-9014c.appspot.com',
    iosBundleId: 'com.example.mvpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzojrqeECx2DurObJ8g4xATh7tEcdys0Y',
    appId: '1:551512181966:web:ad0f822851706a8217149f',
    messagingSenderId: '551512181966',
    projectId: 'tp-mvp-9014c',
    authDomain: 'tp-mvp-9014c.firebaseapp.com',
    storageBucket: 'tp-mvp-9014c.appspot.com',
    measurementId: 'G-535ZLJ16EB',
  );
}
